# Generated by Django 4.2.5 on 2023-09-19 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0006_alter_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='model',
        ),
    ]
