# Generated by Django 4.2.5 on 2023-09-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0010_remove_product_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='price',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
